In [2]:
import numpy as np

In [3]:
# 补充 ： reshape

In [9]:
a = np.arange(1,10).reshape(3,3)

In [10]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# 1.数组之间的运算

In [16]:
a = np.arange(1,10).reshape(3,3)
b = np.arange(1,10).reshape(3,3)
c = np.arange(1,13).reshape(3,4)

In [12]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
# 数组相加 相减 (对应位相加相减)

In [14]:
a + b

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [15]:
a - b

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [17]:
a - c 

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 

In [38]:
# 数组 相乘相除(对应位相乘相除)

In [18]:
a * b

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [19]:
a / b 

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [41]:
# 需要注意：数组之间操作，维度需一致

# 2.矩阵之间运算

In [45]:
# 矩阵 只能是二维
# 数组 可以是多个维度
# 矩阵是数组的子集

In [20]:
a 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
matrix_a = np.matrix(a)
matrix_b = np.matrix(b)

In [24]:
matrix_a

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [25]:
matrix_b

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [26]:
matrix_a + matrix_b

matrix([[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]])

In [29]:
matrix_a - matrix_b 

matrix([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [63]:
# 矩阵之间的乘法，
# d.dot(e)

# 其中d 的列数，必须与 e 的行数一致

In [30]:
d = np.matrix(np.arange(12).reshape(3,4))
e = np.matrix(np.arange(12).reshape(4,3))

In [31]:
d

matrix([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [32]:
e

matrix([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [33]:
d.dot(e)

matrix([[ 42,  48,  54],
        [114, 136, 158],
        [186, 224, 262]])

In [34]:
f = np.matrix(np.arange(12).reshape(3,4))

In [35]:
f

matrix([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [36]:
d.dot(f)

ValueError: shapes (3,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)