In [3]:
import numpy as np

# 1.数组的合并

In [ ]:
# np.concatenate 连接数组
# axis = 0 垂直方向堆叠数组
# axis = 1 水平方向堆叠数组

In [4]:
a = np.arange(6).reshape(2,3)
b = np.arange(3).reshape(1,3)
c = np.arange(10).reshape(2,5)

In [5]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [6]:
b

array([[0, 1, 2]])

In [7]:
c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [8]:
np.concatenate([a,b],axis = 0)

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2]])

In [10]:
np.concatenate([a,c],axis = 1)

array([[0, 1, 2, 0, 1, 2, 3, 4],
       [3, 4, 5, 5, 6, 7, 8, 9]])

In [32]:
# np.vstack()
# vertical
# 垂直方向堆叠数组

# 注意：两个数组，需要有相同的列数

In [11]:
np.vstack([a,b])

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2]])

In [33]:
# np.hstack()
# Horizontal
# 水平方向堆叠数组

# 注意：两个数组，需要有相同的行数

In [12]:
np.hstack([a,c])

array([[0, 1, 2, 0, 1, 2, 3, 4],
       [3, 4, 5, 5, 6, 7, 8, 9]])

# 2.数组的分割

In [34]:
# np.split()
# indices_or_sections 

# 1.如果“索引或区段”是整数N，则数组将沿着“轴”被分成N个相等的数组。如果N无法整除，则会引发一个错误
# 2. [2, 5]

  # ary[:2]
  # ary[2:5]
  # ary[5:]
    
# axis 分割的轴，axis 默认为0

In [13]:
ary = np.arange(9)

In [14]:
ary

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
np.split(ary,[2,5])

[array([0, 1]), array([2, 3, 4]), array([5, 6, 7, 8])]

In [19]:
X = np.arange(16).reshape(4,4)

In [20]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [22]:
np.split(X,2,axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [23]:
np.split(X,2,axis=1)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]